### ISSUE TITLE
Spotify authorization doesn't last.

### ISSUE THREAD

**Issue by LanthaNide93** [AudioBand/AudioBand#42] opened 2022-01-12 22:00 UTC
Hello,

Here is the issue point by point.
## Description
In Spotify Audio Source mode, when I click any button (except play/pause, forward, backward), the player just reopens the terminal for a split second then firefox saying "Spotify Authorization was successful". Except it doesn't seem to be successful as it does that every time I click on the mini-player controls.
I followed the full Spotify setup carefully and for some reason, the backward and forward buttons do work. The play button works too but doesn't switch to the pause icon and clicking it again in an attempt to pause makes Spotify say it "can't play this right now", probably because the player is asking to play the current song when it's already playing.

## How To Reproduce
Steps to reproduce the behaviour:
1. Setup the Spotify audio source following the manual.
2. Click on the 'shuffle' or 'loop' button
3. AudioBand opens firefox with "Spotify Authorization was successful"
4. Click on the button again and AudioBand opens firefox again + the action is not sent to the Spotify app.

## Version
 - Windows Pro 21H1
 - AudioBand Version [e.g. 1.1.0]
 - Spotify for Windows 1.1.76.447.g11f432d8 with Premium Family subscription

## Logs/Screenshots Attachment
[AudioBand.log](https://github.com/AudioBand/AudioBand/files/7858237/AudioBand.log)

Thanks in advance for the help.

**Comment by svr333** [comment] 2022-01-12 22:01
@LanthaNide93 do you have spotify premium?

**Comment by LanthaNide93** [comment] 2022-01-12 22:03
Ah yes sorry, I do have Spotify Premium (Family)

**Comment by svr333** [comment] 2022-01-12 22:07
oh thats no problem, it's just that you require to have premium to use the buttons so thats why I asked;
Ill take a further look in a minute!

**Comment by svr333** [comment] 2022-01-12 23:03
The issue is that all requests to the api fail, but the local ones still work.
A simple pc restart (or manual explorer.exe restart; open task manager -> find explorer.exe -> right click -> restart) might fix it

If not ill take a deeper look

**Comment by LanthaNide93** [comment] 2022-01-13 16:34
Hi again,
Tried restarting windows explorer + restarting windows completely, the result seems to be the same.
Here is the new log.
[AudioBand.log](https://github.com/AudioBand/AudioBand/files/7864332/AudioBand.log)

**Comment by svr333** [comment] 2022-01-13 17:03
Thank you for the info; I already know what the issue is but I have no idea how it is caused.
I'll try my best to find out though

**Comment by LanthaNide93** [comment] 2022-01-13 17:17
Weird that no one else is reporting this. Thanks already for the help. I'll wait for the fix while using the workaround.

**Comment by svr333** [comment] 2022-01-13 19:36
I would like to find out what your current settings are, but this would contain sensitive info.
Could you send a screenshot of `settings.json` with your client id/secret and refresh token blurred out?

To open your raw settings from `settings.json`:
Open AudioBand Settings -> Top Right, click `About` -> On the side click `Open Settings Folder` -> `settings.json`

If you would find direct guidance easier (Discord screenshare for example), you're also welcome to join that [HERE](https://discord.gg/yWDHdH2za5)

------------------
This issue seems to be for you alone, and I have no idea how it occured so I would love to find out and prevent it for other users in the future too

**Comment by svr333** [comment] 2022-01-13 21:11
Resolved in dms

**Closed by svr333** 2022-01-13 21:11 UTC
Labels: bug
