### ISSUE TITLE
Spotify Controls Not Working

### ISSUE THREAD

**Issue by MineTech99** [AudioBand/AudioBand#143] opened 2024-07-24 16:13 UTC
**Spotify Controls not working**
I recently updated to the new audioband update this and since then my audioband controls have stopped working on spotify (NO controls are working. I have switched to Windows 10 Source which does work but then it randomly switches to any other source from windows like a YT video playing.

**Checked common issues**
- I have Reinstalled the program.
- I suspected my custom made skin so i switched to default one but still doesnt work!
- I have double checked the spotify controls installing process still no luck!

**Screenshots**
Spotify as source:
![image](https://github.com/user-attachments/assets/ce00984c-1efb-46c1-a9bd-b590750be9c9)

Windows as Source:
![image](https://private-user-images.githubusercontent.com/86554155/351779148-18cf31b7-cd4d-4314-a6b1-3a429f127110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Mzc1NDAsIm5iZiI6MTcyMTgzNzI0MCwicGF0aCI6Ii84NjU1NDE1NS8zNTE3NzkxNDgtMThjZjMxYjctY2Q0ZC00MzE0LWE2YjEtM2E0MjlmMTI3MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE2MDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMjFmYzRiYjU2OTJlOTY0NzBhMjliMzY0YzM2ZDlkYWU5ZjIyMGUxNjI1MTdiNWE1ZTcwMzViMDQwNWRkMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2tX9fGtZT0mZuXW8QQoKON2GP4XlQTaKTzysJDjCLXA)

Logs attachment
[AudioBand.log](https://github.com/user-attachments/files/16364322/AudioBand.log)

Extra
Btw if you can redirect me to a page where i can upload my skin would be helpful, Thanks.

**Comment by svr333** [comment] 2024-07-24 16:14
Duplicate of #141

**Closed by svr333** 2024-07-24 16:14 UTC
Labels: bug

**Comment by MineTech99** [comment] 2024-07-24 16:20
ok
