### ISSUE TITLE
Cannot Connect with Spotify

### ISSUE THREAD

**Issue by PetrikM** [AudioBand/AudioBand#41] opened 2022-01-06 23:13 UTC
Every time I try to connect with the Spotify dashboard, I have the same issue. Once I select my audio source as Spotify, I get redirected to a white page with plain text saying 

> INVALID_CLIENT: Invalid redirect URI

I have no clue how to fix this. It worked before I clean wiped my windows and I can't get it to work now. Idk if this is an issue on Spotify's end but could someone please help me out?

**Comment by svr333** [comment] 2022-01-06 23:14
You forgot a step in the guide:
> Go to the app you created and click Edit Settings. Add http://localhost/ as a redirect url.

**Comment by PetrikM** [comment] 2022-01-09 21:29
> 
Sorry, forgot to include that I followed every step in the AudioBand setup guide. I added the redirect URL. Thanks

**Comment by svr333** [comment] 2022-01-10 00:53
It works now? @PetrikM

**Comment by PetrikM** [comment] 2022-01-10 01:01
No. I have triple checked all of the steps were followed and the issue is persisting.

**Comment by svr333** [comment] 2022-01-10 12:21
When you go to your app on the Spotify Developer Dashboard, click the green Edit Settings button and you go down to redirect urls, have you entered `http://localhost/` there?

Because that is the only way this issue occurs.

**Comment by svr333** [comment] 2022-01-13 14:31
@PetrikM any updates?

**Comment by svr333** [comment] 2022-01-17 23:00
Im gonna close this issue as Im certain this is just a step missed in the setup.
In case it isn't, please retry by making a new app on the spotify dashboard.

If it still doesn't work; feel free to re-open the issue.

**Closed by svr333** 2022-01-17 23:00 UTC
Labels: bug

**Comment by ClandestineClout** [comment] 2022-01-25 12:06
Same issue. Yes I went to the spotify Developer Dashboard, click the green Edit Settings button and went to redirect urls and entered http://localhost/ there

**Comment by svr333** [comment] 2022-01-25 12:18
You have to put http://localhost/ in the redirect urls, http://localhost won't work

**Comment by ClandestineClout** [comment] 2022-01-25 12:49
Hmm. So I managed to get it working by making sure it had a slash behind it. I'm pretty sure I did that yesterday so I'm tempted to say something happened overnight, but I could have just been careless and forgotten it. Well, now there's a new problem, actually:

 This localhost page can’t be found - No webpage was found for the web address: http://localhost/?code=[really long random letter/number string]

**Comment by svr333** [comment] 2022-01-25 14:56
This is a new error, I'll have a look as soon as I have some time (currently doing exams)

**Comment by YosefBayoude** [comment] 2022-09-18 21:05
![Capture d’écran 2022-09-18 230322](https://user-images.githubusercontent.com/55576351/190928025-e39705a9-08ae-44c1-9cb4-9a64a7f9e77b.png)
I seem to have the same problem, I also followed the instructions, I managed to authorize, but then every time it seems to want to poll, this page opens up in the browser.

**Comment by svr333** [comment] 2022-09-21 14:51
I cannot seem to figure out what this issue means, though do you have a custom iis setup?
That might be interfering with the authorization, you should be able to bypass by temporarily disabling iis or changing the callback port in AudioBand Settings

**Comment by YosefBayoude** [comment] 2022-09-22 19:52
Yup; thank you for your help. You were right, changing the port did help, it now works as intended when setting the audio source to Spotify.

**Comment by svr333** [comment] 2022-09-22 20:22
Glad to hear it works now

**Comment by chiguire** [comment] 2022-10-26 16:36
Yes, having a custom IIS setup might interfere with the port that AudioBand uses, I just changed the AudioBand Callback Port and it worked fine
