### ISSUE TITLE
missing play/pause button in profile "Default (Compact)"

### ISSUE THREAD

**Issue by ArjeSchapiro** [AudioBand/AudioBand#109] opened 2023-05-24 12:22 UTC
## Description
Installation worked like a charm. 
Error occurred after System reboot. Play/pause button works when in any different profile. 
Only doesn't show when in Profile "Compact (Default)". 

Re-installation didn't fix issue. Rebooting/restarting the taskbar (see .bat file attached) also didn't fix issue.

## Version
 - Windows version 22H2; 19045.2846 Windows 10 Enterprise
 - AudioBand Version 1.2.1

[AudioBand.log](https://g
![AudioBandMissingButton](https://github.com/AudioBand/AudioBand/assets/125971882/fa7b79c0-f0ef-4e8a-9f69-c192a5a53b0f)
ithub.com/AudioBand/AudioBand/files/11554395/AudioBand.log)
[restarttaskbar.txt](https://github.com/AudioBand/AudioBand/files/11554466/restarttaskbar.txt)

**Comment by svr333** [comment] 2023-05-24 12:28
Would you mind translating the German error? (I forgot to disable localization in the error messages)
![image](https://github.com/AudioBand/AudioBand/assets/35664724/b2b51404-bfb1-4c33-9430-36ec12c74450)

**Comment by ArjeSchapiro** [comment] 2023-05-24 12:53
2023-05-24 14:03:40.5750 | ERROR | AudioSource(Spotify) |
System.Net.Http.HttpRequestException: Fehler beim Senden der Anforderung.
---> System.Net.WebException: Die zugrunde liegende Verbindung wurde
geschlossen: Unbekannter Fehler beim Empfangen.. --->
System.ComponentModel.Win32Exception: Der Client und der Server können
keine Daten austauschen, da sie nicht über einen gemeinsamen Algorithmus
verfügen

Translation:
2023-05-24 14:03:40.5750 | ERROR | AudioSource(Spotify) |
System.Net.Http.HttpRequestException: Error while sending the request. --->
System.Net.WebException: The underlying connection has been closed: Unknown
error while receiving... ---> System.ComponentModel.Win32Exception: The
client and server cannot exchange data, because they do not have/share the
same algorithmen.

Thank you :)

**Comment by svr333** [comment] 2023-05-25 13:08
Thank you! I will look into this once I have some time, but Im currently dealing with exams so it might be a few weeks.
Sorry for the inconvenience!

Something you can maybe try is to go to %appdata%/AudioBand and delete everything in there (do note this gets rid of all current settings and profiles). (You can also try to delete only audioband.settings or only the profiles)
And then restarting the taskbar might solve it, its basically a clean install.

Because on first glance at this issue it looks very weird and have not seen it before, so it might resolve it just by doing a clean install.

**Comment by ArjeSchapiro** [comment] 2023-06-13 11:11
Hello,

honestly I haven't tried your solution...
But deleting/uninstalling the broken profile in the AudioBand Profile
Settings (Community Profiles) solved the problem.

Thank you for developing this helpful tool ^^

Greetings,
Arje

**Comment by svr333** [comment] 2023-06-13 13:21
I will close this as I was not able to reproduce the issue and it seems like an edge case.

**Closed by svr333** 2023-06-13 13:21 UTC
Labels: bug

**Comment by ArjeSchapiro** [comment] 2023-06-13 13:25
yes, thanks again
